---
title: "Diet-Type cleaning"
author: "Helen Nguyen"
date: "2025-02-19"
output: html_document
---

```{r}
library(dplyr)
library(readr)
```

```{r}
dietHabits <- read_delim("Dietary Habits Survey Data.csv")

dietHabits <- dietHabits %>%
  select(Age, Gender, DietType, Weekly_food_intake_Sweet_foods, Weekly_food_intake_Salty_foods) %>%
  filter(Age == "35-44" | Age == "45-54" | Age == "55-64" | Age == "Above 65")
head(dietHabits)

sum(is.na(dietHabits)) ## output is 0


```

```{r}
heart <- read_delim("heart_failure_clinical_records_dataset.csv")
head(heart, 5)

heart <- heart %>% 
  select(age, diabetes, high_blood_pressure, sex, DEATH_EVENT)

head(heart, 5)

heart <- heart %>% 
  mutate(sex = ifelse(sex==1, "MALE", "FEMALE"),
         DEATH_EVENT = ifelse(DEATH_EVENT==1, "yes", "no"),
         diabetes = ifelse(diabetes == 1, "yes", "no"),
         high_blood_pressure = ifelse(high_blood_pressure == 1, "yes", "no"),
         age = ifelse(age >= 35 & age <= 44, "35-44", 
         ifelse(age >= 45 & age <= 54, "45-54", 
                ifelse(age >= 55 & age <= 64, "55-64", "Above 65")
                )
         )
         )
names(heart)[names(heart) == "sex"] <- "Gender"
heart


```

