---
title: "info201project"
author: "Helen Nguyen"
date: "2025-02-19"
output: html_document
---

```{r}
# 1. Loading Data
library(tidyverse)
library(readxl)
MHI <- read_delim("MedianHouseholdIncome2015.csv", show_col_types = FALSE)
PK <- read_delim("PoliceKillingsUS.csv", show_col_types = FALSE)
Race <- read_delim("ShareRaceByCity.csv", show_col_types = FALSE)
Pop <- read_excel("nst-est2019-01.xlsx")

head(MHI)
head(PK)
head(Race)

nrow(MHI)
nrow(PK)
nrow(Race)

## renaming the two columns for Pop data set
names(Pop)[names(Pop) == "table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts)"] <- "state"
names(Pop)[names(Pop) == "...9"] <- "popEst2015"
Pop$state <- str_remove(Pop$state, "^\\.") # Gets rid of the "." in the data for States


# Gets rid of the first few rows & only shows states abbreviations and population during 2015
Pop <- Pop %>%
  select(state, popEst2015) %>%
  slice(-(1:8)) %>%
  mutate(state = state.abb[match(state, state.name)], 
                            state = replace(state, 9, "DC"))

head(Pop)
nrow(Pop)
```


```{r}
# 2. Handling missing values

## MHI has missing income values which have been cleaned.
MHI_clean <- MHI %>%
  filter(!is.na(`Median Income`) & `Median Income` != "(X)" & `Median Income` != "-")
nrow(MHI_clean)

Pop_clean <- Pop %>%
    filter(!is.na(state) & !is.na(popEst2015))
nrow(Pop_clean)

## Police Killings does not have any missing values for state and city.
## Race data set does not have any missing values either.

```

```{r}
# RQ01 : 1.	What is the relationship between median household income and police killings in US cities?

# Merging data sets
## Step 01: Standardize column names
income_data <- MHI_clean %>%
  rename(state = `Geographic Area`)

police_killings <- PK %>%
  rename(state = state)

income_data

## Step 02: Counting the number of Incidents per state
PK_numbers <- PK %>%
  group_by(state)%>%
  summarise(num_incidents = n(), .groups = "drop")

head(PK_numbers)

## Step 03: Calculating average income per state
income_data <- income_data %>%
  mutate(`Median Income` = as.numeric(`Median Income`))
  
state_income <- income_data %>%
  group_by(state) %>%
  summarise(avg_median_income = mean(`Median Income`, na.rm = TRUE))

head(state_income)

## Step 04: Identified the key value = state.

## Step 05: Merged
merged_income_incident <- left_join(PK_numbers, state_income , by = "state") %>%
  merge(Pop_clean, by = "state")

merged_income_incident <- merged_income_incident %>%
  mutate(log_killings = log(num_incidents + 1))

head(merged_income_incident)

```

```{r}
# Plotting the merged data sets to answer RQ01
ggplot(merged_income_incident, aes(x = avg_median_income, y = num_incidents)) +
  geom_point(alpha = 0.6, color = "red") +
  ylim(0, 100) +
  geom_smooth(method = "lm", se = TRUE, color = "blue") + 
  labs(
    title = "Police Killings vs. Median Income on State Level (2015)",
    x = "Average Median Household Income (USD) in 2015",
    y = "Total Police Violence Incidents"
  ) +
  theme_minimal()
```

```{r}
#testing co-relation
cor.test(merged_income_incident$avg_median_income, merged_income_incident$num_incidents, method = "pearson")

```